### ISSUE TITLE
Define the Meeting Room Management project

### ISSUE THREAD

**Issue by bbalet** [pnc-virtual-company/VC#11]
* [x] Folder structure in Google Drive.
* [x] Kick off meeting.
* [x] List of requirements.
* [x] Workload/List of tasks (common, mandatory, and extra).
* [x] Description of Tasks for students.
* [x] Description of Tasks for teachers.

**Comment by matthieuderoo** [comment]
Kick-off meeting : https://docs.google.com/presentation/d/1Z7izRhLr4Cx6xsYwf3Gj1qiN8LfgOSCna-2s4C2DlRo/edit
