### ISSUE TITLE
Presentation to PNC Staff

### ISSUE THREAD

**Issue by bbalet** [pnc-virtual-company/VC#4]
* [x] Prepare a Powerpoint.
* [x] WEP coordinator validates the Powerpoint.
* [x] Presentation to PNC Staff.

**Comment by channakchhon** [comment]
I have already made the first draft of the slide presentation.
@matthieuderoo Please kindly check it and feel free to give comments or make changes. 
https://docs.google.com/presentation/d/1n0TkB3kJC72qpHAJhkSjG2DulAANR3cLMB5dfvwUTVw/edit?usp=sharing
